### ISSUE TITLE
OrcidAuthorityValueServiceImpl does not account for the label_* ORCID authority values

### ISSUE THREAD

**Issue by uofmsean** [atmire/ORCID-rest-api#3] opened 2020-04-09 21:33 UTC
The [find()](https://github.com/atmire/expanded-ORCID-support/blob/4711d2724523451276b7e037abbb959993259f3f/dspace/modules/additions/src/main/java/com/atmire/dspace/authority/OrcidAuthorityValueServiceImpl.java#L25) method override in [OrcidAuthorityValueServiceImpl.java](https://github.com/atmire/expanded-ORCID-support/blob/stable_6x/dspace/modules/additions/src/main/java/com/atmire/dspace/authority/OrcidAuthorityValueServiceImpl.java) does not account for the label_* values like the proposed fix for [DS-3999](https://jira.lyrasis.org/browse/DS-3999). The suggested approach (in [PR 2195](https://github.com/DSpace/DSpace/pull/2195)) is to set the label_* values in the overridden Orcidv2AuthorityValue [setValues()](https://github.com/atmire/expanded-ORCID-support/blob/4711d2724523451276b7e037abbb959993259f3f/dspace/modules/additions/src/main/java/org/dspace/authority/orcid/Orcidv2AuthorityValue.java#L244) method. However, the overridden [find()](https://github.com/atmire/expanded-ORCID-support/blob/4711d2724523451276b7e037abbb959993259f3f/dspace/modules/additions/src/main/java/com/atmire/dspace/authority/OrcidAuthorityValueServiceImpl.java#L25) method does not call AuthorityValueServiceImpl [fromSolr()](https://github.com/DSpace/DSpace/blob/813800ce1736ec503fdcfbee4d86de836788f87c/dspace-api/src/main/java/org/dspace/authority/AuthorityValueServiceImpl.java#L180) which then calls the setValues() method.

**Comment by uofmsean** [comment] 2020-06-05 16:03
After reviewing this further, I see now that since the find() method is calling the AuthorityValue() sub-class constructors using the Solr document, eventually setValues() is called by the AuthorityValue base class. However, since this patch also includes a new Orcidv2AuthorityValue.java, if you have PR 2195 applied, it will be overridden by this patch which does not include the changes to setValues().

**Comment by uofmsean** [comment] 2020-06-05 21:48
To add to the problems, since the AuthorityValue.java constructor calls setValues(), which can be overridden, the Orcidv2AuthorityValue setValues() method (with PR 2195 applied) fails when calling addOtherMetadata() because otherMetadata is not initialized yet. Attempts to add the additional label_* metadata from the Solr index won't work until otherMetadata is initialized. This actually appears to be a DSpace bug since constructors are not supposed to call methods that can be overridden.

**Comment by jonas-atmire** [comment] 2020-06-25 08:40
@uofmsean, I have applied [PR 2195](https://github.com/DSpace/DSpace/pull/2195) to one of our local testing instances that also had this patch installed, and could indeed reproduce the problem that the otherMetadata was not initialised, resulting in a NullPointerException when trying to access the information that should be retained in it.

As you mentioned, this seems to be a DSpace bug rather than a bug in this patch specifically, since that would undoubtably also happen on a 'default' DSpace instance once the PR is merged. (My guess is that this problem would also occur on the latest DSpace 6_x versions afterwards).
To reduce merging problems later on, it might be best to try and address this in the community (Since the PR is still open).
Afterwards, if a user applies this particular patch, it would:
* Apply as is with an older Dspace6_x version
* Have a small difference in application that needs to be merged. (Which can be addressed in the documentation when the PR is ready/merged)

I am closing this issue until further notice.
Once the PR is merged, we can look into it further if need be

**Closed as completed by jonas-atmire** 2020-06-25 08:40 UTC

**Comment by J4bbi** [comment] 2021-04-26 10:46
Hi there

Just wondering if there's reason to re-open this. [PR 2710](https://github.com/DSpace/DSpace/pull/2710) introduced the same code changes to Orcidv2AuthorityValue as the DS-3999 PR so it is included in dspace-6_x already.

Do I understand correctly that NPEs are likely if the current dspace-6_x patch of the Expanded Support code is applied?

Just tagging: @bram-atmire, @jonas-atmire
